<?php

namespace ArtisanBR\Adminx\Common\App\Models;

use ArtisanBR\Adminx\Common\App\Libs\Support\Str;
use ArtisanBR\Adminx\Common\App\Models\Bases\EloquentModelBase;
use ArtisanBR\Adminx\Common\App\Models\Generics\Configs\MenuConfig;
use ArtisanBR\Adminx\Common\App\Models\Traits\HasUriAttributes;
use ArtisanBR\Adminx\Common\App\Models\Traits\HasValidation;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Query\Builder;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;
use Spatie\Menu\Laravel\Menu as SpatieMenu;
use Spatie\Menu\Link;

class Menu extends EloquentModelBase
{
    use HasUriAttributes, HasValidation;

    protected $fillable = [
        'title',
        'slug',
        'site_id',
        'account_id',
        'user_id',
        'config',
    ];

    protected $casts = [
        'title'  => 'string',
        'slug'   => 'string',
        'config' => MenuConfig::class,
    ];

    //region VALIDATIONS
    public static function createRules(FormRequest $request = null): array
    {
        return [
            'title' => ['required'],
            'slug'  => [
                'required',
                Rule::unique('menus')->ignore($request->id)->where(function (Builder $query) use ($request) {
                    return $query->where('site_id', Auth::user()->site_id);
                }),
            ],
        ];
    }

    public static function createMessages(FormRequest $request = null): array
    {
        return [
            'title.required' => 'O título do menu é obrigatório',
            'slug.required'  => 'O apelido do menu é obrigatório',
            'slug.unique'    => 'O apelído do menu deve ser único entre os menus do site.',
        ];
    }
    //endregion

    //region HELPERS
    public function mount(callable $callback = null): SpatieMenu|string
    {

        $menuBuilder = SpatieMenu::new()->addClass($this->config->menu_class ?? '');

        $menuParentItems = $this->parent_items;

        foreach ($this->parent_items as $menuItem){
            $menuBuilder = $menuItem->mount($menuBuilder);
        }

        return $menuBuilder->each(function (SpatieMenu $submenu) {
            $submenu->addParentClass($this->config->menu_item_submenu_class ?? '');
            $submenu->addParentClass($this->config->menu_item_class ?? '');
        })->each(function (Link $link) {
            $link->prepend($this->config->menu_item_prepend ?? '');
            $link->append($this->config->menu_item_append ?? '');
            $link->addParentClass($this->config->menu_item_class ?? '');
        });


    }
    //endregion

    //region ATTRIBUTES
    protected function html(): Attribute
    {
        return Attribute::make(get: fn() => $this->mount()->render());
    }

    protected function slug(): Attribute
    {
        return Attribute::make(set: static fn($value) => Str::slug(Str::replaceNative([
                                                                                    'menu-',
                                                                                    'menu ',
                                                                                    'menu',
                                                                                ],    '', Str::lower($value))));
    }
    //endregion

    //region OVERRIDES
    public function save(array $options = [])
    {
        //Apelido
        if (empty($this->slug)) {
            $this->slug = $this->title;
        }

        return parent::save($options); // TODO: Change the autogenerated stub
    }
    //endregion

    //region RELATIONS
    public function items()
    {
        return $this->hasMany(MenuItem::class, 'menu_id', 'id')->orderBy('parent_id')->orderBy('position');
    }

    public function parent_items()
    {
        return $this->items()->where('parent_id', null)->orderBy('position');
    }

    public function site()
    {
        return $this->belongsTo(Site::class);
    }

    public function user()
    {
        return $this->hasOne(User::class, 'id', 'user_id');
    }
    //endregion
}
