<?php

namespace Adminx\Common\Models\VisitTracker;

use Adminx\Common\Models\Interfaces\OwneredModel;
use Adminx\Common\Models\Scopes\WhereSiteScope;
use Adminx\Common\Models\Traits\HasOwners;
use Adminx\Common\Models\Traits\Relations\BelongsToPage;
use Adminx\Common\Models\Traits\Relations\BelongsToSite;
use Adminx\Common\Models\Traits\Relations\BelongsToUser;

class Session extends TrackerBase implements OwneredModel
{
    use BelongsToUser, BelongsToSite, BelongsToPage, HasOwners;

    protected $table = 'tracker_sessions';

    protected $fillable = [
        'uuid',
        'user_id',
        'site_id',
        'page_id',
        'device_id',
        'language_id',
        'agent_id',
        'client_ip',
        'cookie_id',
        'referer_id',
        'geoip_id',
        'is_robot',
    ];

    protected array $ownerTypes = ['site','user'];

    /*public function user()
    {
        return $this->belongsTo($this->getConfig()->get('user_model'));
    }*/

    protected static function booted()
    {
        //static::addGlobalScope(new WhereSiteScope);
    }

    public function save(array $options = [])
    {
        parent::save($options); // TODO: Change the autogenerated stub
    }

    public function device()
    {
        return $this->belongsTo($this->getConfig()->get('device_model'));
    }

    public function language()
    {
        return $this->belongsTo($this->getConfig()->get('language_model'));
    }

    public function agent()
    {
        return $this->belongsTo($this->getConfig()->get('agent_model'));
    }

    public function referer()
    {
        return $this->belongsTo($this->getConfig()->get('referer_model'));
    }

    public function geoIp()
    {
        return $this->belongsTo($this->getConfig()->get('geoip_model'), 'geoip_id');
    }

    public function cookie()
    {
        return $this->belongsTo($this->getConfig()->get('cookie_model'), 'cookie_id');
    }

    public function log()
    {
        return $this->hasMany($this->getConfig()->get('log_model'));
    }

    public function getPageViewsAttribute()
    {
        return $this->log()->count();
    }

    public function users($minutes, $result)
    {
        $query = $this
            ->select(
                'user_id',
                $this->getConnection()->raw('max(updated_at) as updated_at')
            )
            ->groupBy('user_id')
            ->from('tracker_sessions')
            ->period($minutes)
            ->whereNotNull('user_id')
            ->orderBy($this->getConnection()->raw('max(updated_at)'), 'desc');

        if ($result) {
            return $query->get();
        }

        return $query;
    }

    public function userDevices($minutes, $result, $user_id)
    {
        $query = $this
            ->select(
                'user_id',
                $this->getConnection()->raw('max(updated_at) as updated_at')
            )
            ->groupBy('user_id')
            ->from('tracker_sessions')
            ->period($minutes)
            ->whereNotNull('user_id')
            ->orderBy($this->getConnection()->raw('max(updated_at)'), 'desc');

        if ($result) {
            return $query->get();
        }

        return $query;
    }
}
