<?php
/*
 * Copyright (c) 2024. Tanda Interativa - Todos os Direitos Reservados
 * Desenvolvido por Renalcio Carlos Jr.
 */

namespace Adminx\Common\Models;

use Adminx\Common\Exceptions\FrontendException;
use Adminx\Common\Models\Bases\EloquentModelBase;
use Adminx\Common\Models\Casts\AsFormElementCollection;
use Adminx\Common\Models\Generics\Configs\FormConfig;
use Adminx\Common\Models\Traits\Relations\BelongsToSite;
use Carbon\Carbon;

class FormAnswer extends EloquentModelBase
{
    use BelongsToSite;

    protected $fillable = [
        'site_id',
        'form_id',
        'form_config',
        'form_elements',
        'data',
        'events',
        'origin_url',
        'origin_ip',
    ];

    protected $casts = [
        'form_config' => FormConfig::class,
        'form_elements' => AsFormElementCollection::class,
        'data' => 'object',
        'created_at' => 'datetime:d/m/Y H:i:s',
    ];


    protected $attributes = [
        //'form_config' => [],
        //'form_elements' => [],
    ];

    //region OVERRIDES
    /**
     * @throws FrontendException
     */
    public function save(array $options = []): bool
    {
        if($this->origin_ip && self::whereSiteId($this->site_id)->whereOriginIp($this->origin_ip)->whereDate('created_at', Carbon::today())->count() > 10){
            throw new FrontendException('Parece que você já respondeu a este formulário algumas vezes hoje, tente novamente outro dia, evite spams.', 401);
        }

        return parent::save($options); // TODO: Change the autogenerated stub
    }
    //endregion

    //region RELATIONS
    public function form(){
        return $this->belongsTo(Form::class);
    }
    //endregion
}
